jobs:
  deploy:
    parameters:
      stack-name:
        type: string
    executor: sam/default
    steps:
      - run: echo "hello world"
      - run: echo << parameter.stack-name >>
orbs:
  sam: circleci/aws-sam-serverless@1.0.1
version: 2.1
workflows:
  version: 2
#   dev:
#     jobs:
#       - deploy:
#           stack-name: FleetManagementDev
#           filters:
#             branches:
#               only:
#                 - master
#   beta:
#     jobs:
#       - deploy:
#           stack-name: FleetManagementBeta
#           filters:
#             tags:
#               only:
#                 - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)-beta$/
#             branches:
#               ignore:
#                 - /.*/
  prod:
    jobs:
      - hold-for-approval:
          type: approval
          filters:
            branches:
              only:
                - master
            branches:
              ignore:
                - /.*/
      - deploy:
          requires:
            - hold-for-approval
          stack-name: FleetManagementProd
